# Exported from Render on 2026-07-07T15:26:02Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: ttg-doc-standardizer
      runtime: docker
      repo: https://github.com/roninPb65/ttg-doc-standardizer
      plan: free
      envVars:
      - key: property
        sync: false
      - key: fromDatabase
        sync: false
      - key: value
        sync: false
      - key: envVars
        sync: false
      - key: sizeGB
        sync: false
      - key: mountPath
        sync: false
      - key: disk
        sync: false
      - key: autoDeploy
        sync: false
      - key: healthCheckPath
        sync: false
      - key: dockerfilePath
        sync: false
      - key: rootDir
        sync: false
      - key: runtime
        sync: false
      - key: name
        sync: false
      - key: services
        sync: false
      - key: postgresMajorVersion
        sync: false
      - key: region
        sync: false
      - key: plan
        sync: false
      - key: databases
        sync: false
      region: oregon
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
